apiVersion: v1
kind: pod
metadata:
  name: annotations-demo
  labels:
    app: roboshop
    environment: dev
    purpose: poc
  annotations:
    description: "This is a demo pod to showcase annotations in Kubernetes."
    owner: "DevOps Team"
    mongo_url: "mongodb://mongo:27017/roboshop"
spec:
  containers:
    - name: nginx
      image: nginx